rem * -------------------------------------------------------------------
rem *
rem *  Purpose:  Convert a Xml File to a Cobol Data file using Cobol Copybook 
rem *   Author:  RecordEditor~CodeGen
rem * Language:  Windows bat
rem * Packages:  CobolToXml (https://sourceforge.net/projects/coboltoxml)
rem *            JRecord    (https://sourceforge.net/projects/jrecord/)
rem *            Cb2Xml     (https://sourceforge.net/projects/cb2xml/)
rem *        
rem * *------------- Keep this notice in your final code ---------------
rem * *   This code was generated by JRecord projects CodeGen program
rem * *            on the: 22 Jun 2016 8:25:33 
rem * *     from Copybook: DTAR020.cbl
rem * *           Dialect: FMT_MAINFRAME
rem * *          Template: batCbl2Xml
rem * *             Split: SPLIT_NONE   
rem * * File Organization: IO_FIXED_LENGTH   
rem * *              Font: cp037
rem * *   
rem * *    CodeGen Author: Bruce Martin
rem * *-----------------------------------------------------------------

rem java -jar ../lib/Xml2Cobol.jar  -cobol G:/Users/Bruce01/RecordEditor_HSQL/CopyBook/Cobol/DTAR020.cbl
../lib/Xml2Cobol.bat   -cobol G:/Users/Bruce01/RecordEditor_HSQL/CopyBook/Cobol/DTAR020.cbl ^
                           -fileOrganisation FixedWidth ^
                           -font cp037 ^
                       -input  out/DTAR020.bin.xml ^
                       -output out/DTAR020.bat.bin
                       
