rem * -------------------------------------------------------------------
rem *
rem *  Purpose:  Convert a cobol Data file using Cobol Copybook to Xml
rem *   Author:  RecordEditor~CodeGen
rem * Language:  Windows bat  
rem *        
rem * *------------- Keep this notice in your final code ---------------
rem * *   This code was generated by JRecord projects CodeGen program
rem * *            on the: 2 Jun 2016 15:31:27 
rem * *     from Copybook: amsPoDownload.cbl
rem * *           Dialect: FMT_MAINFRAME
rem * *          Template: batCbl2Xml
rem * *             Split: SPLIT_01_LEVEL   
rem * * File Organization: IO_BIN_TEXT   
rem * *              Font: 
rem * *   
rem * *    CodeGen Author: Bruce Martin
rem * *-----------------------------------------------------------------

java -jar ../lib/Cobol2Xml.jar -cobol G:/Users/Bruce01/RecordEditor_HSQL/Copybook/Cobol/amsPoDownload.cbl ^
                                   -fileOrganisation Text ^
                                   -split 01 ^
                                   -recordSelection PO-Record  Record-Type=H1 ^
                                   -recordSelection Product-Record  Record-Type=D1 ^
                                   -recordSelection Location-Record  Record-Type=S1 ^
                               -input  G:/Users/Bruce01/RecordEditor_HSQL/SampleFiles/Ams_PODownload_20041231.txt   ^
                               -output out/Ams_PODownload_20041231.txt.xml
pause