rem * -------------------------------------------------------------------
rem *
rem *  Purpose:  Convert a cobol Data file using Cobol Copybook to Xml
rem  *   Author:  RecordEditor~CodeGen
rem * Language:  Java Script (jjs interpreter that comes with java 8/9)  
rem *        
rem * *------------- Keep this notice in your final code ---------------
rem * *   This code was generated by JRecord projects CodeGen program
rem * *            on the: 26 May 2016 15:16:46 
rem * *     from Copybook: DTAR020.cbl
rem * *           Dialect: FMT_MAINFRAME
rem * *          Template: batCbl2Xml
rem * *             Split: SPLIT_NONE   
rem * * File Organization: IO_FIXED_LENGTH   
rem * *              Font: cp037
rem * *   
rem * *    CodeGen Author: Bruce Martin
rem * *-----------------------------------------------------------------


java -jar ../lib/Cobol2Xml.jar -cobol G:/Users/Bruce01/RecordEditor_HSQL/Copybook/Cobol/DTAR020.cbl -fileOrganisation FixedWidth  ^
                                 -font cp037 ^
                             -input  G:/Users/Bruce01/RecordEditor_HSQL/SampleFiles/DTAR020.bin   ^
                             -output out/xxxDTAR020.bin.xml 
 
pause